server:
  port: 8085

spring:
  application:
    name: user-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bmshop?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: wen175924
  redis:
    host: 192.168.72.130
    port: 6379
    password: 123456
  rabbitmq:
    host: 192.168.72.130
    virtual-host: /bmshop
    username: bmshop
    password: 123456
    # 指定交换机
    template:
      exchange: BMSHOP.SMS.EXCHANGE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    # 心跳时间
    lease-renewal-interval-in-seconds: 5
    # 过期时间
    lease-expiration-duration-in-seconds: 15

mybatis:
  type-aliases-package: com.banmingi.bmshop.user.pojo
