server:
  port: 8083

spring:
  application:
    name: search-service
  main:
    allow-bean-definition-overriding: true
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.72.130:9300


eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    # 拉取微服务时间
    registry-fetch-interval-seconds: 10
  instance:
    # 心跳时间
    lease-renewal-interval-in-seconds: 5
    # 过期时间
    lease-expiration-duration-in-seconds: 15