server:
  port: 10010

spring:
  application:
    name: gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5

zuul:
  prefix: /api
  routes:
    # 路由到商品微服务
    item-service: /item/**
    #用这种配置方式才能使跳转到upload后路径上还有/upload
    upload-service:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false
    # 路由到搜索微服务
    search-service: /search/**
    # 路由到用户服务
    user-service: /user/**
    # 路由到授权服务
    auth-service: /auth/**
    # 路由到购物车服务
    cart-service: /cart/**
  add-host-header: true
  sensitive-headers:  # 覆盖默认敏感头信息

bmshop:
  jwt:
    pubKeyPath: C:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: BM_TOKEN

  #路由拦截白名单
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item
      - /api/upload