server:
  port: 10010

spring:
  application:
    name: gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5

zuul:
  prefix: /api
  routes:
    # 路由到商品微服务
    item-service: /item/**
